---
- hosts: localhost
  gather_facts: no
  tasks:

    - name: Get VCenter / ESXi info
      vmware_about_info:
        hostname: '{{ vsphere_server }}'
        username: '{{ vsphere_username }}'
        password: '{{ vsphere_password }}'
        validate_certs: no
      delegate_to: localhost
      register: vcenter_about_info

    - name: Get VCenter / ESXi resource pool info
      vmware_resource_pool_info:
        hostname: '{{ vsphere_server }}'
        username: '{{ vsphere_username }}'
        password: '{{ vsphere_password }}'
        validate_certs: no
      delegate_to: localhost
      register: vcenter_rp_info

    - name: Get VCenter / ESXi disk pool info
      vmware_datastore_info:
        hostname: '{{ vsphere_server }}'
        username: '{{ vsphere_username }}'
        password: '{{ vsphere_password }}'
        #        datacenter:name: '{{ vsphere_datacenter }}'
        validate_certs: no
      delegate_to: localhost
      register: vcenter_disk_info

    - debug:
        msg: '{{ vcenter_about_info }}'
      delegate_to: localhost

    - debug:
        msg: '{{ vcenter_rp_info }}'
      delegate_to: localhost

    - debug:
        msg: '{{ vcenter_disk_info }}'
      delegate_to: localhost
