    - name: "Deploy extra disks on {{ vm_name }}"
      vmware_guest_disk:
        hostname: "{{ vsphere_server }}"
        username: "{{ vsphere_username }}"
        password: "{{ vsphere_password }}"
        datacenter: "{{ vsphere_datacenter }}"
        validate_certs: False
        folder: "{{ ocp_cluster_folder }}"
        name: "{{ vm_name }}"
        disk:
          - size_gb: "{{ vm_disk_size }}"
            type: "{{ disk_provisioning }}"
            datastore: "{{ datastore }}"
            state: present
            scsi_controller: 1
            unit_number: 1
            scsi_type: "paravirtual"
      delegate_to: localhost

