---
- hosts: OSEv4
  gather_facts: false

  tasks:
    #    - debug:
    #        msg: "{{ hostvars['item'].mac_address }}"
    #      loop: "{{ query('inventory_hostnames', 'masters') }}"
    #- debug:
    #    msg: "{{ hostvars[groups['masters'][0]].mac_address }}"

    - debug:
        msg: "Master Detected : Hostname : {{ hostvars[item].inventory_hostname }} MAC Address : {{ hostvars[item].mac_address }}"
      loop:
        "{{ groups['masters'] }}"

    - debug:
        msg: "Total Masters : {{ groups['masters'] | length }}"

    - debug:
        msg: "Worker Detected : Hostname : {{ hostvars[item].inventory_hostname }} MAC Address : {{ hostvars[item].mac_address }}"
      loop:
        "{{ groups['workers'] }}"

    - debug:
        msg: "Total Workers : {{ groups['workers'] | length }}"

    - name: Provision VM using VMware
      include_tasks: tasks/vmware_provision_vm.yml
      vars:
        vm_function: "master"
        vm_hostname: "{{ hostvars[item].inventory_hostname }}"
        vm_mac_address: "{{ hostvars[item].mac_address }}"
      loop:
        "{{ groups['masters'] }}"

    - name: Provision VM using VMware
      include_tasks: tasks/vmware_provision_vm.yml
      vars:
        vm_function: "worker"
        vm_hostname: "{{ hostvars[item].inventory_hostname }}"
        vm_mac_address: "{{ hostvars[item].mac_address }}"
      loop:
        "{{ groups['workers'] }}"
