---
# This is the directory where the openshift-install file is located
# The install-files-directory will be passed to the installer
# and will contain the resulting ignition files and base64 conversions
ocp4_client_directory: "/home/presutti/bin"
ocp4_client_installer_url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux-4.2.0.tar.gz"
ocp4_client_archive_name: "{{ ocp4_client_installer_url | basename }}"
ocp4_client_sha_url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/sha256sum.txt"

ocp4_installer_directory: "/home/presutti/ocp"
ocp4_installer_filename: "openshift-install"
ocp4_install_config_name: "install-config.yaml"
ocp4_install_files_directory: "{{ ocp4_installer_directory }}/data"
ocp4_installer_url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-install-linux-4.2.0.tar.gz"
ocp4_installer_archive_name: "{{ ocp4_installer_url | basename }}"
ocp4_installer_sha_url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/sha256sum.txt"

# RHCOS OVA image
rhcos_ova_url: 'https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.2/latest/rhcos-4.2.0-x86_64-vmware.ova'
rhcos_ova_archive_name: "{{ rhcos_ova_url | basename }}"
rhcos_ova_sha_url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.2/latest/sha256sum.txt"

# Some combined variable names to make the later tasks easier to write :)
ocp4_client_file_fullarchivename: "{{ ocp4_installer_directory }}/{{ ocp4_client_archive_name }}"
ocp4_install_file_fullname: "{{ ocp4_install_files_directory }}/{{ ocp4_install_config_name}}"
ocp4_installer_file_fullarchivename: "{{ ocp4_installer_directory }}/{{ ocp4_installer_archive_name }}"
rhcos_ova_file_fullname: "{{ ocp4_installer_directory }}/{{ rhcos_ova_archive_name }}"

# Cluster Variables
base_domain: "internal.yourdomain.com"
cluster_name: ocp4

vsphere_server: "vcenter.internal.yourdomain.com"
vsphere_username: "administrator@internal.yourdomain.com"
vsphere_password: "test123"
vsphere_datacenter: "datacenter"
vsphere_datastore: "datastore"
ocp_cluster_folder: "ocp4"
rhcos_template_name: "RHCOS"
rhcos_template_vm_network: "VM Network"

# Pull secret is obtained from try.openshift.com
pull_secret: '{"auths": ...}'

# Provide an SSH public key for installation onto the nodes. Username is
# Core for CoreOS nodes.
ssh_key: 'ssh-ed25519 AAAA...'

# Web Server URL (for hosting the bootstrap.ign)
bootstrap_url: "https://webserver.internal.yourdomain.com/ocp/bootstrap.ign"

# Node creation defaults
node_memory_mb: 32768
node_num_cpus: 8
node_num_cpu_cores_per_socket: 4

# Cluster node counts - Will be overwritten based on inventory
cluster_master_replicas: 3
cluster_worker_replicas: 0
