- name: "Create the {{ oracle_group }} Group"
  group: 
    name: "{{ oracle_group }}" 
    state: present

- name: Create the oracle User
  user:
    name: "{{ oracle_user }}" 
    group: "{{ oracle_group }}" 
    state: present
    update_password: always
    password: "$6$mysecretsalt$lxylT5/9wlw9WuBfvTqwo3NjO1PJwZTV4KVGSAIe2xlTgChgaK.4sJh2y2OtiDFettZkCfZcdvLXfeutyXaxA."
  register: oracle_user_profile

- debug:
    var: oracle_user_profile

- name: Create Oracle Directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ oracle_user }}" 
    group: "{{ oracle_group }}" 
  with_items:
    - "{{ oracle_home_dir }}"
    - "{{ oracle_middleware_dir }}"
    - "{{ oracle_config_domain_dir }}"
    - "{{ oracle_config_app_dir }}"
    - "{{ oracle_software_dir }}"
    - "{{ oracle_inventory_home_dir }}"

- name: Remove existing Oracle variables file
  file:
    path: "{{ oracle_user_profile.home }}/{{ oracle_env_file }}"
    state: absent

- name: Add variables to oracle environment file for the Oracle user
  blockinfile:
    path: "{{ oracle_user_profile.home }}/{{ oracle_env_file }}"
    state: present
    create: yes
    owner: "{{ oracle_user }}" 
    group: "{{ oracle_group }}" 
    mode: 0755
    block: |
      export MW_HOME={{ oracle_middleware_dir }}
      export WLS_HOME=$MW_HOME/wlserver
      export WL_HOME=$WLS_HOME
      # Set to the appropriate JAVA_HOME.
      export JAVA_HOME={{ java_home_dir }}
      export PATH=$JAVA_HOME/bin:$PATH

- name: Add environment file to user profile
  blockinfile:
    path: "{{ oracle_user_profile.home }}/{{ user_profile }}"
    state: present
    create: yes
    owner: "{{ oracle_user }}" 
    group: "{{ oracle_group }}" 
    insertbefore: BOF
    mode: 0755
    block: |
      if [ -f ~/{{ oracle_env_file }} ]; then
        . ~/{{ oracle_env_file }}
      fi

- name: Warn user of existing logins
  debug:
    msg: Profile for the Oracle user has been updated, any existing logins will need to log in again to recognize the changes.
  
