- name: Remove existing response files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ response_file_wli }}"
    - "{{ response_file_mw }}"
    - "{{ orainst_inventory_file }}"

- name: Create WLI response file from template
  template:
    src: wls.rsp.j2
    dest: "{{ response_file_wli }}"
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"
    mode: 0644

- name: Create Fusion Middleware response file from template
  template:
    src: fmw_infr.rsp.j2
    dest: "{{ response_file_mw }}"
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"
    mode: 0644

- name: Create Oracle Inventory location file from template
  template:
    src: oraInst.loc.j2
    dest: "{{ orainst_inventory_file }}"
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"
    mode: 0644

