- name: Extract WLI ZIP file
  unarchive:
    src: "{{ app_mount_dir.path }}/{{ nfs_server_subdir }}/{{ wli_filename }}"
    dest: "{{ oracle_software_dir }}"
    remote_src: true

- name: Install WLI using response file
  shell: "source ~/{{ user_profile }} && $JAVA_HOME/bin/java -Xmx1024m -jar {{ oracle_software_dir }}/{{ wli_installer_jar  }} -silent -responseFile {{ response_file_wli }} -invPtrLoc {{ orainst_inventory_file }}"
  become: yes
  become_user: "{{ oracle_user }}"

- name: Install Fusion Middleware if option is selected
  block:
  - name: Extract FMW ZIP file
    unarchive:
      src: "{{ app_mount_dir.path }}/{{ nfs_server_subdir }}/{{ fmw_filename }}"
      dest: "{{ oracle_software_dir }}"
      remote_src: true

  - name: Install FMW using response file
    shell: "source ~/{{ user_profile }} && $JAVA_HOME/bin/java -Xmx1024m -jar {{ oracle_software_dir }}/{{ fmw_installer_jar  }} -silent -responseFile {{ response_file_fmw }} -invPtrLoc {{ orainst_inventory_file }}"
    become: yes
    become_user: "{{ oracle_user }}"

  when: install_fusion_middleware == True
