- name: Create mount point for Applications
  file:
    path: "{{ app_mount_dir.path }}"
    state: directory
    mode: '0755'

- name: Mount NFS Share
  mount:
    path: "{{ app_mount_dir.path }}"
    src: "{{ nfs_server_mountpoint }}"
    fstype: nfs
    state: mounted

- name: Ensure JDK installer exists
  stat:
    path: "{{ app_mount_dir.path }}/WLI/jdk-8u211-linux-x64.rpm"
    get_checksum: false
    get_md5: false
    get_mime: false
  register: jdk_state

- name: Fail if JDK Installer doesn't exist
  fail:
    msg: "JDK Installer file does not exist! Please check NFS share"
  when: jdk_state.stat.exists == false

- name: Ensure WLI installer exists
  stat:
    path: "{{ app_mount_dir.path }}/{{ nfs_server_subdir }}/{{ wli_filename }}"
    get_checksum: false
    get_md5: false
    get_mime: false
  register: installer_state

- name: Fail if WLI Installer doesn't exist
  fail:
    msg: "WLI Installer file does not exist! Please check NFS share"
  when: installer_state.stat.exists == false

