---
galaxy_info:
    author: Ed Presutti
    description: Install and configure OCP 4.1 on vSphere w/ vCenter (automate the UPI process)
    company: Ed's Demo Lab
    license: Apache License 2.0
    min_ansible_version: 2.0
    platforms:
    - name: EL
      versions:
      - 7
    categories:
    - system
    dependencies: []

