---
galaxy_info:
    author: Ed Presutti
    description: Power a previously built OCP 4 cluster on or off
    company: Ed's Demo Lab
    license: Apache License 2.0
    min_ansible_version: 2.0
    platforms:
    - name: EL
      versions:
      - 7
      - 8
    categories:
    - system
    dependencies: []

