# TODO: Add validate certs option in inventory / defaults

  - name: Download and validate installer
    import_tasks: download_installer.yml

  - name: Create installer configuration files
    import_tasks: create_install_config.yml

  - name: Create template in VMware
    import_tasks: vmware_create_template.yml
    when: "deploy_ova"

  - name: Setup Host List
    set_fact:
      vm_list: "{{ query('inventory_hostnames', 'bootstrap:masters:workers', wantlist=True) }}"

  - include_tasks: vmware_remove_vms.yml
    with_items: "{{ vm_list }}"
    loop_control:
      loop_var: vm_name

  - include_tasks: vmware_create_vms.yml
    with_items: "{{ vm_list }}"
    loop_control:
      loop_var: vm_name

  - include_tasks: vmware_set_vm_metadata.yml
    with_items: "{{ vm_list }}"
    loop_control:
      loop_var: vm_name
  
  - include_tasks: vmware_change_mac_addresses.yml
    with_items: "{{ vm_list }}"
    loop_control:
      loop_var: vm_name

  - name: Create client files directory if it doesn't exist
    file:
      path: "{{ ocp4_client_directory }}"
      state: directory
      mode: 0755

  - name: Extract Openshift Client
    unarchive:
      src: "{{ ocp4_client_file_fullarchivename }}"
      dest: "{{ ocp4_client_directory }}"
      remote_src: true
    when: "deploy_client"
