
  - name: Download and validate installer
    import_tasks: download_installer.yml

  - name: Create installer configuration files
    import_tasks: create_install_config.yml

# TODO: Currently disabled as the VMware Deploy OVF module doesn't seem to like the OCP OVA. 
# Could be my cluster too so feel free to comment.
#  - name: Create template in VMware
#    import_tasks: vmware_create_template.yml

  - name: Setup Host List
    set_fact:
      vm_list: "{{ query('inventory_hostnames', 'bootstrap:masters:workers', wantlist=True) }}"

  - include_tasks: vmware_remove_vms.yaml
    with_items: "{{ vm_list }}"
    loop_control:
      loop_var: vm_name

  - include_tasks: vmware_create_vms.yaml
    with_items: "{{ vm_list }}"
    loop_control:
      loop_var: vm_name

  - include_tasks: vmware_set_vm_metadata.yaml
    with_items: "{{ vm_list }}"
    loop_control:
      loop_var: vm_name
  
  - include_tasks: vmware_change_mac_addresses.yaml
    with_items: "{{ vm_list }}"
    loop_control:
      loop_var: vm_name

