- name: Remove existing install configuration file (it should be gone already)
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ ocp4_install_file_fullname }}"

- name: Count nodes for install-config
  set_fact:
    cluster_master_replicas: "{{ groups['masters'] | length }}"
    cluster_worker_replicas: "{{ groups['workers'] | length }}"

- name: Create openshift-install install-config file from template
  template:
    src: "{{ template_install_config }}"
    dest: "{{ ocp4_install_file_fullname }}"
    mode: 0644

- name: Extract Openshift Installer
  unarchive:
    src: "{{ ocp4_installer_file_fullarchivename }}"
    dest: "{{ ocp4_installer_directory }}"
    remote_src: true

- name: Execute Openshift Installer
  command:
    argv:
      - "{{ ocp4_installer_directory }}/{{ ocp4_installer_filename }}"
      - "--dir"
      - "{{ ocp4_install_files_directory }}"
      - "create"
      - "ignition-configs"
  register: ocp4_installer_output

- name: STDOUT output from openshift_install
  debug: 
    var: ocp4_installer_output.stdout_lines

- name: STDERR output from openshift_install
  debug: 
    var: ocp4_installer_output.stderr_lines

- name: Create append-bootstrap Ignition file from template
  template:
    src: "{{ template_append_bootstrap }}"
    dest: "{{ ocp4_install_files_directory }}/append-bootstrap.ign"
    mode: 0644

- name: Read bootstrap metadata and convert to base64
  slurp:
    src: "{{ ocp4_install_files_directory }}/append-bootstrap.ign"
  register: metadata_bootstrap_result

- name: Read master metadata and convert to base64
  slurp:
    src: "{{ ocp4_install_files_directory }}/master.ign"
  register: metadata_master_result

- name: Read worker metadata and convert to base64
  slurp:
    src: "{{ ocp4_install_files_directory }}/worker.ign"
  register: metadata_worker_result

