
      - name: Remove previous MAC address list file
        file:
          path: "{{ mac_address_list_destination_filename }}"
          state: absent

      - name: Write MAC addresses to file
        lineinfile:
          dest: "{{ mac_address_list_destination_filename }}"
          line: "{{ vm_name }} : {{ item.mac_address }}"
          create: yes
        with_items:
          - "{{ vm_guest_facts.virtual_machines | json_query(query) }}"
        vars:
          query: "[?guest_name=='{{ vm_name }}']"
