    - name: "Deploy Starting Metadata on {{ vm_name }}"
      vmware_guest:
        hostname: "{{ vsphere_server }}"
        username: "{{ vsphere_username }}"
        password: "{{ vsphere_password }}"
        datacenter: "{{ vsphere_datacenter }}"
        datastore: "{{ vsphere_datastore }}"
        esxi_hostname: "{{ vsphere_esxi_hostname if vsphere_use_esxi_hostname else omit}}"
        cluster: "{{ vsphere_cluster if vsphere_use_cluster else omit}}"
        validate_certs: False
        folder: "{{ ocp_cluster_folder }}"
        state: "present"
        name: "{{ vm_name }}"
        vapp_properties:
          - id: "disk.EnableUUID"
            type: boolean
            value: 'True'
            operation: edit
          - id: "guestinfo.ignition.config.data.encoding"
            type: string
            value: "base64"
            operation: edit
      delegate_to: localhost

    - name: "Deploy {{ vm_metadata_type }} metadata on {{ vm_name }}"
      vmware_guest:
        hostname: "{{ vsphere_server }}"
        username: "{{ vsphere_username }}"
        password: "{{ vsphere_password }}"
        datacenter: "{{ vsphere_datacenter }}"
        datastore: "{{ vsphere_datastore }}"
        esxi_hostname: "{{ vsphere_esxi_hostname if vsphere_use_esxi_hostname else omit}}"
        cluster: "{{ vsphere_cluster if vsphere_use_cluster else omit}}"
        validate_certs: False
        folder: "{{ ocp_cluster_folder }}"
        state: "present"
        name: "{{ vm_name }}"
        vapp_properties:
          - id: "guestinfo.ignition.config.data"
            type: string
            value: "{{ vm_metadata_data }}"
            operation: edit
      delegate_to: localhost

    - name: "Setting Guest OS ID on {{ vm_name }} to {{ vmware_guest_os_id }}"
      vmware_guest:
        hostname: "{{ vsphere_server }}"
        username: "{{ vsphere_username }}"
        password: "{{ vsphere_password }}"
        datacenter: "{{ vsphere_datacenter }}"
        datastore: "{{ vsphere_datastore }}"
        esxi_hostname: "{{ vsphere_esxi_hostname if vsphere_use_esxi_hostname else omit}}"
        cluster: "{{ vsphere_cluster if vsphere_use_cluster else omit}}"
        validate_certs: False
        guest_id: "{{ vmware_guest_os_id }}"
        folder: "{{ ocp_cluster_folder }}"
        state: "present"
        name: "{{ vm_name }}"
      delegate_to: localhost

