  - name: Change network adapter settings of virtual machine
    vmware_guest_network:
      hostname: "{{ vsphere_server }}"
      username: "{{ vsphere_username }}"
      password: "{{ vsphere_password }}"
      datacenter: "{{ vsphere_datacenter }}"
      validate_certs: no
      name: "{{ vm_name }}"
      gather_network_info: false
      networks:
        - label: "Network adapter 1"
          state: present
          manual_mac: "{{ hostvars[vm_name].mac_address }}"
    delegate_to: localhost
    register: network_info
